services:
  webapplication1:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "8111:8111"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8111
      - DISPLAY=:1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./uBlock:/uBlock
    ipc: host
